return {
  ["workshop-1207269058"]={
    configuration_options={
      ddon=true,
      hbcolor="dynamic",
      hblength=10,
      hbpos=1,
      hbstyle="heart",
      value=true
    },
    enabled=true
  },
  ["workshop-358749986"]={
    configuration_options={ IndicatorSize=3, MaxIndicator=7000, PlayerIndicators=1 },
    enabled=true
  },
  ["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=99 }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true
    },
    enabled=true
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2
    },
    enabled=true
  },
  ["workshop-458940297"]={
    configuration_options={
      DFV_ClientPrediction="default",
      DFV_FueledSettings="default",
      DFV_Language="EN",
      DFV_MinimalMode="default",
      DFV_PercentReplace="default",
      DFV_ShowACondition="default",
      DFV_ShowADefence="default",
      DFV_ShowAType="default",
      DFV_ShowDamage="default",
      DFV_ShowFireTime="default",
      DFV_ShowInsulation="default",
      DFV_ShowTemperature="default",
      DFV_ShowUses="default"
    },
    enabled=true
  },
  ["workshop-609675532"]={
    configuration_options={
      _debug=false,
      despawn_delay=0.1,
      despawn_mode="RANDOM",
      limit_table="def",
      res_mode="MEM"
    },
    enabled=true
  },
  ["workshop-666155465"]={
    configuration_options={ food_estimation=1, food_order=1, food_style=1, lang="en",
show_food_units=0 },
    enabled=true
  }
}
